### ISSUE TITLE
Add austrian mobile phone frequencies into FREQMAN

### ISSUE THREAD

**Issue by chimera234** [furrtek/portapack-havoc#143]
Hello,

Because I am from Austria would be great to have austria mobil phone frequencies in FREQMAN.
For details please refer to below frequency assignment.

https://www.rtr.at/en/tk/FRQshare

Thanks
Chimera

**Comment by chimera234** [comment]
Let´s close this - I added by my own - It´s anyway not something a developer should take care ... :)

Thanks
Chimera

**Comment by fantuz** [comment]
hi @Chimera, what about creating a pull request ?

On Dec 27, 2017 1:49 PM, "chimera234" <notifications@github.com> wrote:

Closed #143 <https://github.com/furrtek/portapack-havoc/issues/143>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/furrtek/portapack-havoc/issues/143#event-1402482251>,
or mute the thread

**Comment by fantuz** [comment]
Hello ... what about editing this file and push it to master (pending @furrtek approval) ?
-> https://github.com/furrtek/portapack-havoc/blob/master/sdcard/FREQMAN/POCSAG-2.TXT

For the benefit of the community !

Cheers @chimera234 and keep up the contributions!
