### ISSUE TITLE
captured c16

### ISSUE THREAD

**Issue by mansigen** [furrtek/portapack-havoc#170]
hello everyone and congratulations to furrtek that has made a fantastic firmware ... at the moment I'm trying to capture and analyze the data that are saved on the sd in c16 format. how I can analyze c16 files on computer ? whireshark or similar programs?
thanks a lot :)

**Comment by furrtek** [comment]
Hello :)
I don't think wireshark is able to chew on I/Q files directly. Since I/Q is really the raw data "from the air", you need to demodulate the signal of interest to get binary data, and then you could feed that to protocol decoders like Wireshark.
Specialized programs can do that for specific kinds of modulations. URH and GNU Radio also, they require more work but they're very flexible.

**Comment by mansigen** [comment]
thanks a lot!!!!
I'll try, to install gnu radio on osx

have a nice day;)
