### ISSUE TITLE
I updated the firmware and CPLD, all successfully ,but the screen is always blank, dark no light.

### ISSUE THREAD

**Issue by freeworld1981** [furrtek/portapack-havoc#226]
I updated the firmware and CPLD, all successfully ,but the screen is always blank, dark no light.

the led only green/yellow/red light.

where is the problem?

**Comment by pipi111** [comment]
same problem

**Comment by alphaomicron** [comment]
After updating, the play dead mode may be enabled; this is indicated by a random firmware error, such as the following:

Firmware error 0x14008000

To exit this, press: up - down - left - right - center button. You can disable this by editing: settings -> disable login. The setting will be saved for next time.

**Comment by alphaomicron** [comment]
And also RTFM.

**Comment by kevtheskin** [comment]
Hello there , I am getting the same error. And the exit suggestion does not work? Kev

**Comment by yadox666** [comment]
Same, no fake error code on screen. But my problem does not appear in an original hackrf one and original portapack. In the original kit it works like a charm. But a friend bought a hackrf one clone in aliexpress branded as hackrf one 2014. It's not a problem of the portapack, because when I switched to my original hackrf it worked from the beginning. 

Flashing portpack original software works, but when flashing portapack havoc bin it does not boot, it shows black screen, no logo, and in dmesg it does not appear any new device. I tried to reflash dfu, calibration data and spi flash without success. So there must be some chinese cloned hackrf boards with some problems. Maybe spi size? No more ideas to test. Thank you and congratulations for your development and work.

**Comment by hkn300** [comment]
i had same problem , some how latest build not working (i got latest Chinese colones.). i am just getting black screen. but got luck older build  works for me, but functionality not great. like you said after many many  unsuccessful boot finally i was able to see menus , after reset just black screen. i am currently stuck with older version . had some performances issue
