### ISSUE TITLE
Feature request: GPS Simulator

### ISSUE THREAD

**Issue by tommy5467** [furrtek/portapack-havoc#305]
Would it possible to add a GPS Simulator function? I saw some Chinese clones have it in some firmware. THX.

**Comment by furrtek** [comment]
The Chinese clones "GPS Simulator" menu item is just a barely modified version of the IQ file replay app.

**Comment by tommy5467** [comment]
Thank you so much for your time!

**Comment by jamesshao8** [comment]
Hi, I am trying to duplicate this (gridrf version). I modified replay myself, since they are not open source.I made replay working with C8 and sample rate of 2MHz. However, when I was trying to send out the signal, the spectrum is a little different and cell phone can't lock onto that signal.

Can you give me some advice? I will post my code on github. I hereby post the spectrum with gridrf transmitting and my own (4x 8x oversample rate).
GridRF
![20200214145625852](https://user-images.githubusercontent.com/17997195/74510082-f168d480-4f3d-11ea-8e38-57d3663e5b3c.png)
Mine 4x
![20200214150239247](https://user-images.githubusercontent.com/17997195/74510091-f594f200-4f3d-11ea-9223-7fff5841c0a0.png)
Mine 8x
![2020021415033030](https://user-images.githubusercontent.com/17997195/74510100-f9c10f80-4f3d-11ea-8bb8-c2a9d74d774d.png)

When I was using 4x sample rate, my cell phone can receive some of the gps signal, but can't lock. When using 8x sample rate, none of the satellite signal can be received.
![20200214150255110](https://user-images.githubusercontent.com/17997195/74510166-1fe6af80-4f3e-11ea-9699-baabf8ec6a78.jpg)

**Comment by jamesshao8** [comment]
https://github.com/jamesshao8/portapack-havoc-modified/blob/master/firmware/baseband/proc_gps_sim.cpp
https://github.com/jamesshao8/portapack-havoc-modified/blob/master/firmware/baseband/proc_gps_sim.hpp
https://github.com/jamesshao8/portapack-havoc-modified/blob/master/firmware/application/apps/gps_sim_app.cpp
https://github.com/jamesshao8/portapack-havoc-modified/blob/master/firmware/application/apps/gps_sim_app.hpp

This is my modification of the code. Please give me some advice. Thank you.
@furrtek

**Comment by jamesshao8** [comment]
nevermind, I have already fixed it.

**Comment by BreakSecurity** [comment]
@jamesshao8 please try to do a pull request ;)

**Comment by jamesshao8** [comment]
Hi @BreakSecurity I dont know how to pull my code here, I guess it requires furrtek's consent, right?
You can check the code in my repository:
https://github.com/jamesshao8/portapack-havoc-modified
or you can directly try my firmware here.
portapack-h1-havoc-gps.zip
